### ISSUE TITLE
NATS to Mongodb (vise versa)

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [damianiandrea/mongodb-nats-connector#3]
Hello,
This is really neat work, did you think about the other way around? means syncing messages from NATS/JetStream to Mongodb so that the connector becomes bi-directional similar to what ClickHouse have: https://clickhouse.com/docs/en/engines/table-engines/integrations/nats#table_engine-redisstreams-creating-a-table? 

If contribution is open, i can start and submit a PR..

**Comment by damianiandrea** [comment]
Hi @ahmed-adly-khalil,

Thanks a lot for your feedback, I'm glad you like the connector!

Regarding your question: I built the connector with the intent of simply sinking the data from MongoDB to NATS, but I think it would be quite cool to make it bidirectional (sourcing data from NATS to MongoDB). In fact, another user already proposed something similar.

Contributions are welcome! But since supporting bidirectional communication between NATS and MongoDB is not trivial, I invite you to share how you would implement that, and maybe discuss the approach together, before submitting a PR.

**Comment by damianiandrea** [comment]
Hi, @ahmed-adly-khalil!

Forgive me for the very late response, life got in the way! :)

I think for now I'll close this issue, I'd like to focus on the current functionality of the connector, add more tests, measure its performance, and see what could be improved. After the current implementation is solid and works well, I might come back to this and pick up where we left off!

Thanks a lot for the feedback you gave so far!
